a1:
# order:
# FL
# FR
# RL
# RR
  model_name: "model_0522.pt"
  num_observations: 45
  clip_obs: 100.0
  clip_actions_lower: [-100, -100, -100, 
                       -100, -100, -100, 
                       -100, -100, -100, 
                       -100, -100, -100] 
  clip_actions_upper: [100, 100, 100, 
                       100, 100, 100, 
                       100, 100, 100, 
                       100, 100, 100] 
  rl_kp: [20, 20, 20, 
          20, 20, 20, 
          20, 20, 20, 
          20, 20, 20] 
  rl_kd: [0.5, 0.5, 0.5, 
          0.5, 0.5, 0.5, 
          0.5, 0.5, 0.5, 
          0.5, 0.5, 0.5] 
  fixed_kp: [80, 80, 80, 
             80, 80, 80, 
             80, 80, 80, 
             80, 80, 80] 
  fixed_kd: [3, 3, 3, 
             3, 3, 3, 
             3, 3, 3, 
             3, 3, 3] 
  hip_scale_reduction: 0.5
  hip_scale_reduction_indices: [0, 3, 6, 9]
  num_of_dofs: 12
  action_scale: 0.25
  lin_vel_scale: 2.0
  ang_vel_scale: 0.25
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  commands_scale: [2.0, 2.0, 0.5]
  torque_limits: [33.5, 33.5, 33.5, 
                  33.5, 33.5, 33.5, 
                  33.5, 33.5, 33.5, 
                  33.5, 33.5, 33.5] 
  default_dof_pos: [ 0.1000, 0.8000, -1.5000, 
                    -0.1000, 0.8000, -1.5000, 
                     0.1000, 1.0000, -1.5000, 
                    -0.1000, 1.0000, -1.5000] 
  joint_names: ["FL_hip_joint", "FL_thigh_joint", "FL_calf_joint",
                "FR_hip_joint", "FR_thigh_joint", "FR_calf_joint",
                "RL_hip_joint", "RL_thigh_joint", "RL_calf_joint",
                "RR_hip_joint", "RR_thigh_joint", "RR_calf_joint"]
