a1:
  model_name: "model_0501.pt"
  num_observations: 45
  clip_obs: 100.0
  clip_actions: 100.0
  # damping: 0.5
  # stiffness: 20.0
  p_gains: [20, 20, 20, # FL
            20, 20, 20, # FR
            20, 20, 20, # RL
            20, 20, 20] # RR
  d_gains: [0.5, 0.5, 0.5, # FL
            0.5, 0.5, 0.5, # FR
            0.5, 0.5, 0.5, # RL
            0.5, 0.5, 0.5] # RR
  action_scale: 0.25
  hip_scale_reduction: 0.5
  num_of_dofs: 12
  lin_vel_scale: 2.0
  ang_vel_scale: 0.25
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  torque_limits: [33.5, 33.5, 33.5, # FL
                  33.5, 33.5, 33.5, # FR
                  33.5, 33.5, 33.5, # RL
                  33.5, 33.5, 33.5] # RR
  default_dof_pos: [ 0.1000, 0.8000, -1.5000, # FL
                    -0.1000, 0.8000, -1.5000, # FR
                     0.1000, 1.0000, -1.5000, # RL
                    -0.1000, 1.0000, -1.5000] # RR
  joint_names: ["FL_hip_joint", "FL_thigh_joint", "FL_calf_joint",
                "FR_hip_joint", "FR_thigh_joint", "FR_calf_joint",
                "RL_hip_joint", "RL_thigh_joint", "RL_calf_joint",
                "RR_hip_joint", "RR_thigh_joint", "RR_calf_joint"]

cyberdog1:
  model_name: "model.pt"
  num_observations: 45
  clip_obs: 100.0
  clip_actions: 100.0
  # damping: 0.5
  # stiffness: 20.0
  p_gains: [20, 20, 20, # FL
            20, 20, 20, # FR
            20, 20, 20, # RL
            20, 20, 20] # RR
  d_gains: [0.5, 0.5, 0.5, # FL
            0.5, 0.5, 0.5, # FR
            0.5, 0.5, 0.5, # RL
            0.5, 0.5, 0.5] # RR
  action_scale: 0.25
  hip_scale_reduction: 0.5
  num_of_dofs: 12
  lin_vel_scale: 2.0
  ang_vel_scale: 0.25
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  torque_limits: [24.0, 24.0, 24.0, # FL 
                  24.0, 24.0, 24.0, # FR
                  24.0, 24.0, 24.0, # RL
                  24.0, 24.0, 24.0] # RR
  default_dof_pos: [ 0.1000, 0.8000, -1.5000, # FL
                    -0.1000, 0.8000, -1.5000, # FR
                     0.1000, 1.0000, -1.5000, # RL
                    -0.1000, 1.0000, -1.5000] # RR
  joint_names: ["FL_hip_joint", "FL_thigh_joint", "FL_calf_joint",
                "FR_hip_joint", "FR_thigh_joint", "FR_calf_joint",
                "RL_hip_joint", "RL_thigh_joint", "RL_calf_joint",
                "RR_hip_joint", "RR_thigh_joint", "RR_calf_joint"]
